###
### This file in YAML format contains key-value pairs to be used by the script during runtime
###

# Set flag to True/False to generate/suppress debug statements to show in console
debug: True

# All input CSV files should be located in the folder designated by input_folder
input_folder: "./input"

# Generated FSH code files will be put to the folder designated by output_folder
output_folder: "./output"

# Instance templates should be located in the folder designated by templates_folder
# The convention is to name each template file with the name of the FHIR resource name or resource profile name
# E.g. To generate FHIR Observation instances, create a template file named Observation.tmpl in the folder
templates_folder: "./templates"

# Specify name of CSV file containing global variables and their values
global_vars_file: global-variables.csv

# Specify one or more jobs to run to generate FSH code files
# To define a job, you specify (1) the resource/profile name, (2) the data file to use, and
# optionaly (3) other input files for creating lookup tables
jobs:
- resource: Patient
  dataFile: Patient.data.csv
  otherInputFiles:
    - Patient.contact.csv
    - Patient.gender.csv

- resource: Observation
  dataFile: Observation.data.csv
  otherInputFiles:
    - Observation.code.csv
    - Observation.valueCode.csv

- resource: Condition
  dataFile: Condition.data.csv
  otherInputFiles:
    - Condition.code.csv

- resource: Practitioner
  dataFile: Practitioner.data.csv

- resource: PractitionerRole
  dataFile: PractitionerRole.data.csv
  otherInputFiles:
    - PractitionerRole.code.csv
    - PractitionerRole.specialty.csv

- resource: Encounter
  dataFile: Encounter.data.csv

- resource: Coverage
  dataFile: Coverage.data.csv

- resource: PriorLevelOfFunction
  dataFile: PriorLevelOfFunction.data.csv

- resource: PriorLevelOfCognitiveFunction
  dataFile: PriorLevelOfCognitiveFunction.data.csv
  otherInputFiles:
    - PriorLevelOfCognitiveFunction.code.csv

- resource: Medication
  dataFile: Medication.data.csv

- resource: MedicationRequest
  dataFile: MedicationRequest.data.csv

- resource: MedicationStatement
  dataFile: MedicationStatement.data.csv

- resource: AllergyIntolerance
  dataFile: AllergyIntolerance.data.csv
  otherInputFiles:
    - AllergyIntolerance.code.csv

- resource: Immunization
  dataFile: Immunization.data.csv
  otherInputFiles:
    - Immunization.cvx.code.csv
    - Immunization.ndc.code.csv

- resource: ObservationVitalSigns
  dataFile: ObservationVitalSigns.data.csv
  otherInputFiles:
    - ObservationVitalSigns.code.csv

- resource: ObservationLab
  dataFile: ObservationLab.data.csv
  otherInputFiles:
    - ObservationLab.code.csv

- resource: ReassessmentTimepointsEncounter
  dataFile: ReassessmentTimepointsEncounter.data.csv

- resource: EpisodeOfCare
  dataFile: EpisodeOfCare.data.csv

- resource: FPCollection
  dataFile: FPCollection.data.csv
  otherInputFiles:
    - FPCollection.code.csv
    - FPCollection.category-functioning.csv
    - FPCollection.category-PFEDomain.csv
    - FPCollection.category-survey.csv
    - FPCollection.performers.csv

- resource: FPObservation
  dataFile: FPObservation.data.csv
  otherInputFiles:
    - FPObservation.code.csv
    - FPObservation.category-functioning.csv
    - FPObservation.category-PFEDomain.csv
    - FPObservation.category-survey.csv
    - FPObservation.category-SocialHistory.csv
    - FPObservation.category-SDOH.csv
    - FPObservation.valueCodeableConcept.csv
    - FPObservation.valueQuantity.csv
    - FPObservation.performers.csv

- resource: Device
  dataFile: Device.data.csv

- resource: DiagnosticReport
  dataFile: DiagnosticReport.data.csv

- resource: FPDeviceUseStatement
  dataFile: FPDeviceUseStatement.data.csv

- resource: Organization
  dataFile: Organization.data.csv

- resource: Location
  dataFile: Location.data.csv
